### ISSUE TITLE
Python 3.5 - Raspi 3 Model B+

### ISSUE THREAD

**Issue by agent2003** [EmbedME/pyUSB2FIR#1]
Hi,

I'm trying to run the view_matplot.py example using python 3.5. 

In usb2fir.py, I've had to change the single / to a double // on line 111 to prevent the error with an invalid indices. This applies to other lines where a single / has been used.

On line 148 I've also changed the long(1) to int(1) or just 1 or python complains. However, I'm now getting a runtime warning saying 'divided by zero encountered in double_scalars' as the a = (a + 00) / (1 << alphaScale) is obviously dividing by zero.

Do you have any ideas? Thanks

https://github.com/EmbedME/pyUSB2FIR/blob/6f9931591f723cb9c8cac989ee76d75c0336c704/pyusb2fir/usb2fir.py#L111

**Comment by EmbedME** [comment]
There were two commits to improve compatibility with python 3:
351fa4f92f03d01a2236370d4b9323425d419554
c8787c879e2b7c0969fedde79dd032edb12c495d
With these changes it works on my system with Python 3.5.2.

**Comment by MartinRobomaze** [comment]
Hi,

I've been trying to run this library on raspberry pi 3B  on python3, and I got the same error. I think it's because raspbian is a 32 bit operating system and when I printed alphaScale, I got value of 34. So that means that you are shifting 1 to right by 34 which is 34 bit number. But when I replace alphaScale with it's value, it somehow works. I really don't know why it works when I hardcode this value, maybe it has something to do with variable types.
